### ISSUE TITLE
When will you release the code?

### ISSUE THREAD

**Issue by liuxinren456852** [rwth-irt/onlineFGO#1]

**Comment by hz658832** [comment]
Hi Xinren,
thank you for your interest. 
I would like to release the code in about 4 weeks because I am still working on the paper that is with the code. 
If you want to try my code with data, we can work out a quick (perhaps dirty) solution. 
Could you tell me more about your case? You can mail me: h.zhang@irt.rwth-aachen.de
Thanks. 
Bests,
Haoming

**Comment by ye-tingfeng** [comment]
Hi, i'm happy to know that your team has plan to release the code, and i'm also waiting to read your Code. Of course, when i can get the Code?

**Comment by wolf943134497** [comment]
@hz658832  Great works! 
Any plan to release the code?
Thanks

**Comment by hz658832** [comment]
Hi @wolf943134497,

Sorry for the (huge) delay since the paper was delayed. 

I would appreciate you having a look at the code and giving it a try. 

Thanks.

Haoming
