### ISSUE TITLE
gnssFGO with LIO

### ISSUE THREAD

**Issue by wolf943134497** [rwth-irt/onlineFGO#2]
@hz658832   Thanks for your great works and released code!

I read your released code,  I found the code that gnssfgo coupled with lio is not included in the released code.

Is that part of the code released? Or I didn’t understand your code？

Thanks a lot!

**Comment by hz658832** [comment]
Hi @wolf943134497,

currently, I have only adapted/used the LIO-SAM, but I did not integrate the LIO-SAM totally into my framework. 

It means that the LiDAR-pre-processing (raw PC -> features) must still be carried out using the LIO-SAM (have a look into the launch run_fgo). As you can see, there is a LIO-SAM folder in the repo.  

Besides, I "put" the LS to calculate the LiDAR-Odometry under include/sensor/lidar/LIOSAM.h. There is an sensor integrator called LIOIntegrator that has an instance of LIOSAM. 

It would be better to get KISS-ICP along with the gnssFGO, perhaps you could give a try. 

Bests,

Haoming

**Comment by wolf943134497** [comment]
@hz658832  Thanks for your quick reply！
I think it is possible to run the LIOSAM (or other odometer algrithm) algorithm offline and record the result？
Then  use this topic directly and integrate lio pose into the gnssfgo framework（use LIOIntegrator  in GraphSensorCentric and GraphTimeCentric).  just update Integrating other sensor code.

**Comment by hz658832** [comment]
Hi  @wolf943134497,
Yes. GraphSensorCentric has yet to be uploaded since it is not my main claim. 
But, as online is the buzzword for onlineFGO, it could be more convincing that one runs everything on the air. Furthermore, if you have pre-processed the LiDAR odoms, there won't be any delay in the LiDAR pre-processing, which questions the main contribution of the time-centric graph optimization.
Cheers,
Haoming
