### ISSUE TITLE
liosam[ERROR] 

### ISSUE THREAD

**Issue by Erika1kuta** [rwth-irt/onlineFGO#3]
Hi, Haoming, thanks for your great work.
I met some problems when I ran

`ros2 launch lio_sam fgorun.launch.py` 

use AC_City_0.db3
 
`[INFO] [launch]: All log files can be found below /root/.ros/log/2024-01-18-20-10-02-800103-16fb1efb275b-383
[INFO] [launch]: Default logging verbosity is set to INFO
urdf_file_name : /root/humble/rwth_gnss/install/lio_sam/share/lio_sam/config/robot.urdf.xacro
[INFO] [static_transform_publisher-1]: process started with pid [384]
[INFO] [lio_sam_imageProjection-2]: process started with pid [386]
[INFO] [lio_sam_featureExtraction-3]: process started with pid [388]
[INFO] [rviz2-4]: process started with pid [390]
[static_transform_publisher-1] [WARN] [1705608602.853141812] []: Old-style arguments are deprecated; see --help for new-style arguments
[rviz2-4] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[lio_sam_imageProjection-2] sensor type velodyne
[lio_sam_imageProjection-2] Test: 1 0 0 -1
[static_transform_publisher-1] [INFO] [1705608603.198204923] [static_transform_publisher_55tJBajTRJd73HkI]: Spinning until stopped - publishing transform
[static_transform_publisher-1] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-1] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-1] from 'map' to 'odom'
[lio_sam_featureExtraction-3] sensor type velodyne
[lio_sam_featureExtraction-3] Test: 1 0 0 -1
[lio_sam_imageProjection-2] [INFO] [1705608603.201152686] [rclcpp]: ----> Image Projection Started.
[lio_sam_featureExtraction-3] [INFO] [1705608603.201676422] [rclcpp]: ----> Feature Extraction Started.
[rviz2-4] [INFO] [1705608603.314269439] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-4] [INFO] [1705608603.314382467] [rviz2]: OpenGl version: 4.5 (GLSL 4.5)
[rviz2-4] [INFO] [1705608603.357050684] [rviz2]: Stereo is NOT SUPPORTED
[lio_sam_imageProjection-2] point time front: -0.099431
[lio_sam_imageProjection-2] point time back: 0.001304
[lio_sam_imageProjection-2] [ERROR] [1705608609.468341680] [lio_sam_imageProjection]: time scan cur: 1648706394.826912 end: 1648706394.828216
[lio_sam_imageProjection-2] point time front: -0.099476
[lio_sam_imageProjection-2] point time back: 0.001304
[lio_sam_imageProjection-2] [ERROR] [1705608609.568095830] [lio_sam_imageProjection]: time scan cur: 1648706394.917659 end: 1648706394.918963
[lio_sam_featureExtraction-3] Size Corner: 408
[lio_sam_featureExtraction-3] Size Surfe: 3340
[lio_sam_imageProjection-2] point time front: -0.099422
[lio_sam_imageProjection-2] point time back: 0.001304
`

and Rviz2 has no images. I am looking forward to your solution. Thanks.

**Comment by hz658832** [comment]
hi @Erika1kuta,
I think the liosam was running as expected. Because this is not a full liosam and I only started the point cloud projection and feature extraction in this launch, You must run the online_fgo at the same time. 

After you have started the irt_gnss_preprocessing and lio_sam, check
`online_fgo/config/aachen_lc/common.yaml` at line 69 
`Integrators: ["IRTPVALCIntegrator",] ` and change it to Integrators: ["IRTPVALCIntegrator",  "LIOIntegrator"]

then you run ros2 launch online_fgo ac_lc.launch
If you have subscribed the correct messages, you should see something in rviz. 
Btw: I would recommend you to also run mapviz for the visualization on google map. 
I am looking for collaborations, so if you are a research associate, maybe we could work together since there are still some points that should be improved for this project. I am also happy to see if someone can adapt my framework for their own applications.
Merci.
Haoming
